### ISSUE TITLE
Server can send private messages to players, but the player's reply causes an error

### ISSUE THREAD

**Issue by VincentGonnet** [ADHDMC/SimplePMs#1]
### How to reproduce :
- type `msg PlayerName test` in the console
- on the PlayerName account in game, use `/reply test`

### Error message :
> Cannot invoke "org.bukkit.entity.Player.getName()" because "recipient" is null

**Comment by RhythmicSys** [comment]
Should be fixed in this next update, have been working on rewriting the plugin, hopefully should be finished soon

**Comment by RhythmicSys** [comment]
![image](https://user-images.githubusercontent.com/45906780/234667771-9ed9a266-d705-4e69-9d0b-b9abcac9dfb0.png)
A release with a fix will be out soon

**Comment by RhythmicSys** [comment]
Fixed as of https://github.com/ADHDMC/SimplePMs/releases/tag/v1.0
